trans2gcast redone. Only with ffmpeg. Multiple functions! :)

diff --git a/bin/trans2gcast b/bin/trans2gcast
--- a/bin/trans2gcast
+++ b/bin/trans2gcast
@@ -1,68 +1,209 @@
 #!/bin/bash
 #
-# Transcode video script for GhromeCast 2 compatibily
+# Transcode video script for ChromeCast 2 compatibily
 #
-# Use:
-# - handbrake-cli
-# - mkvtoolnix
-# - ffmpeg
-# For info:
-# - mediainfo
+# Using ffmpeg!
 #
 
-# Video rate Kbits
-BUFSIZE=20000
-MAXRATE=20000
+# Internal field separator -> "for" statement = new lines
+IFS=$'\n'
 
-# Audio Rate
-AUDRATE=320
+# Colors
+RED='\033[0;31m'
+GREEN='\033[0;32m'
+YELLOW='\033[0;33m'
+BLUE='\033[0;34m'
+MAG='\033[0;35m'
+CYAN='\033[0;36m'
+NC='\033[0m' # No Color
 
-# Uso
-function usage() {
-  echo "Recodificar video para compatibilizar con ChomeCast."
-  echo "	- video: X264 4.2, audio: AAC o MP3."
-  echo
-  echo "Uso:" 
-  echo "	$HOWCALLED <opción> <fuente> <destino>"
-  echo
-  echo "Opciones:"
-  echo " 	-va -> Convierte todo, video y audio."
-  echo " 	-a -> Solo convierte audio"
-}
+# Transcoder options
+# ----------------------------------------------------------------------------
+
+# x264 options
+X264_OPTIONS="-profile:v high -level 4.2 -preset medium -crf 20 -maxrate 16M -bufsize 20M"
+
+# AAC options
+AUDRATE=320k
+
+# Checks command line
+# ----------------------------------------------------------------------------
 
 HOWCALLED=`basename $0`
 
-if [ $# -eq 0 ]
- then
-   usage 
-   exit 1
-fi
-
-
-OPT=$1
-SOUR=$2
-DEST=$3
-
-if [[ -z $SOUR || -z $DEST ]]; then
+# Usage
+function usage() {
+	echo
+	echo -e "${CYAN}Transcode video for ChromeCast v2 compatibility${NC}"
+	echo "	- Container: MKV."
+	echo "	- Video: X264 4.2"
+	echo "	- Audio: AAC or MP3."
+	echo
+	echo "Usage: $HOWCALLED [-e <more ffmpeg options>] <input video> [output video]"
+	echo
+}
+# check number of arguments
+if [[ $# -lt 1 || $# -gt 3 ]]; then
 	usage
 	exit 1
 fi
 
-TITLE=$(basename -s .mkv "$DEST")
+# Title of video and extra options
+if [ "$1" == "-e" ]; then
+	EXTRA="$2"
+	SOUR=$3
+	DEST=$4
+else
+	EXTRA=""
+	SOUR=$1
+	DEST=$2
+fi
+
+if [ -z "$DEST" ]; then
+	DEST=$SOUR
+fi
+FILE=$(basename "$DEST")
+TITLE="${FILE%.*}"
 DEST=""$TITLE" [gcast].mkv"
 
-if [[ "$OPT" == "-va" ]] ; then
-	echo "Convirtiendo AUDIO Y VIDEO..."
-	HandBrakeCLI -i "$SOUR" -t 1 -o "$DEST" -f mkv --crop 0:0:0:0 --loose-anamorphic --modulus 2 -e x264 -q 21 --cfr -a 1 -E av_aac -6 5point1 -R Auto -B "$AUDRATE" -D 0 --gain 0 --audio-fallback ac3 -x vbv-bufsize=$BUFSIZE:vbv-maxrate=$MAXRATE --encoder-level="4.2" --encoder-profile=high --verbose=1
-	mkvpropedit -e info --set title="$TITLE" "$DEST"
-	exit 0
-elif [[ "$OPT" == "-a" ]] ; then
-	echo "Convirtiendo SOLO AUDIO..."
-	ffmpeg -i "$SOUR" -map 0:v -map 0:a -map 0:s -c:v copy -c:a libfdk_aac -b:a "$AUDRATE"k -c:s copy "$DEST"
-	mkvpropedit -e info --set title="$TITLE" "$DEST"
-	exit 0
-else
-	usage
+echo -e "${MAG}Transcoding video for ChromeCast v2 compatibility...${NC}"
+echo -e "${BLUE}------------------------------------------------------------------------------${NC}"
+echo -e "${CYAN}Checking filename ...${NC}"
+echo -e "* Input video: ${GREEN}$SOUR${NC}"
+echo -e "* Output video: ${GREEN}$DEST${NC}"
+echo -e "* Metadata title: ${GREEN}$TITLE${NC}"
+if [ -n "$EXTRA" ]; then
+	echo -e "* Extra ffmpeg options: ${GREEN}$EXTRA${NC}"
+fi
+
+# Checks necessary utilities and ffmpeg options
+# ----------------------------------------------------------------------------
+
+echo -e "${BLUE}------------------------------------------------------------------------------${NC}"
+echo -e "${CYAN}Checking ffmpeg ...${NC}"
+
+# test if `ffmpeg` is available
+FFMPEG=`which avconv || which ffmpeg`
+if [ -z $FFMPEG ]; then
+	echo -e '${RED}ERROR: ffmpeg is not available, please install it!${NC}'
 	exit 1
 fi
 
+echo "* `ffmpeg -hide_banner -version | grep "ffmpeg version"`"
+
+# test ffmpeg options
+echo -n "* Check MKV container format ... "
+if [ `ffmpeg -hide_banner -formats | grep -c "E matroska"` -gt 0 ]; then
+	echo -e "${GREEN} OK${NC}"
+else
+	echo -e "${RED}FAIL!${NC}"
+	echo '  ERROR: ffmpeg without matroska format!'
+	exit 1
+fi
+
+echo -n "* Check x264 the free H.264 Video Encoder ..."
+if [ `ffmpeg -hide_banner -codecs | grep -c "libx264"` -gt 0 ]; then
+	echo -e "${GREEN} OK${NC}"
+else
+	echo -e "${RED}FAIL!${NC}"
+	echo '  ERROR: ffmpeg without H264 codec!'
+	exit 1
+fi
+
+echo -n "* Check AAC Audio Encoder ..."
+if [ `ffmpeg -hide_banner -codecs | grep -c "libfdk_aac"` -gt 0 ]; then
+	A_CODEC="libfdk_aac"
+	echo -e "${GREEN} OK${NC}"
+else
+	echo -e "${RED}FAIL!${NC}"
+	echo -e "${YELLOW}  WARNING: ffmpeg without libfdk. Using AAC native enconder!${NC}"
+	A_CODEC="aac"
+fi
+
+echo -e "* ffmpeg is ${GREEN}OK${NC}"
+
+# Get video info 
+# ----------------------------------------------------------------------------
+
+echo -e "${BLUE}------------------------------------------------------------------------------${NC}"
+echo -e "${CYAN}Source processing. Parsing source streams ...${NC}"
+
+# Put streams in array off lines (trim leading spaces)
+for STR in $(ffmpeg -hide_banner -i "$SOUR" 2>&1 | sed 's/^ *//g')
+do
+	STREAM=$(echo "$STR" | grep Stream)
+	if [ -n "$STREAM" ]; then 
+		echo "* $STREAM" 
+	fi
+	V_INFO="${V_INFO}\n${STR}"
+done
+
+# Error in file
+if [ $(echo -e ${V_INFO} | grep -c "Invalid data found") -gt 0 ]; then
+	echo -e "${RED}ERROR: File $SOUR is NOT A VALID VIDEO FILE!${NC}"
+	exit 1
+fi
+
+# Video
+if [ $(echo -e ${V_INFO} | grep Video: | grep -c h264) -gt 0 ]; then
+	VIDEO="-c:v copy"
+	echo -e "${GREEN}VIDEO:${NC} Already in H264. No transcoding needed."
+else
+	VIDEO="-c:v libx264 $X264_OPTIONS"
+	echo -e "${GREEN}VIDEO:${NC} Transcoding activated to x264."
+fi
+
+# Audio
+N_AUD_STR=`echo -e ${V_INFO} | grep -c Audio:`
+N_AUD_OK=`echo -e ${V_INFO} | grep Audio: | grep -c -E "aac|mp3"`
+AUDIO=""
+if [ $N_AUD_STR -eq $N_AUD_OK ] ; then
+	AUDIO="-c:a copy"
+	echo -e "${GREEN}AUDIO:${NC} Already in compatible format. No transcoding."
+elif [ $N_AUD_STR -eq 1 ] ; then
+	echo -e "${GREEN}AUDIO:${NC} Transcoding activated to AAC."
+	AUDIO="-c:a $A_CODEC -b:a $AUDRATE"
+else
+	echo -e "${GREEN}AUDIO:${NC} Multiple streams detected. Please choose what to do ... "
+	echo -e "  ${YELLOW}Options: [t] transcode (default), [c] copy, [i] ignore.${NC} "
+	i=0
+	for AUD_OPT in $(echo -e ${V_INFO} | grep Audio:)
+	do
+		echo "  $AUD_OPT"
+		echo -ne "${YELLOW}  -> Choose [t,c,i] : ${NC}"
+		read -s -n 1 OPT
+		case $OPT in
+			c) echo -ne "${GREEN}Copying ...${NC}"; AUDIO="$AUDIO -c:a:$i copy";;
+			i) echo -ne "${GREEN}Ignoring (not in output file) ..."${NC}; AUDIO="$AUDIO -map -0:a:$i";;
+			*) echo -ne "${GREEN}Transcoding to aac ..."${NC}; AUDIO="$AUDIO -c:a:$i $A_CODEC -b:a:$i $AUDRATE";;
+		esac
+		let i=i+1
+		echo 
+	done
+	AUDIO=$(echo "$AUDIO" | sed 's/^ *//g')
+fi
+
+# Subtitles
+if [ $(echo -e ${V_INFO} | grep -c Subtitle:) -gt 0 ]; then
+	SUBTITLE="-c:s copy"
+	echo -e "${GREEN}SUBTITLE:${NC} Found, adding all!"
+else
+	SUBTITLE="-sn"
+	echo -e "${GREEN}SUBTITLE:${NC} No subtitles found. :("
+fi
+
+# And finaly, do job
+# ----------------------------------------------------------------------------
+
+echo -e "${BLUE}------------------------------------------------------------------------------${NC}"
+echo -e "${CYAN}Starting transcoding ...${NC}"
+
+CMDLINE="ffmpeg -loglevel error -stats -hide_banner -i \"$SOUR\" -map 0 $VIDEO $AUDIO $SUBTITLE -metadata title=\"$TITLE\" $EXTRA \"$DEST\""
+
+echo -e "* ${GREEN}CMD:${NC} $CMDLINE"
+echo -e "* ${GREEN}$(echo -e ${V_INFO} | grep Duration:)${NC}"
+echo -e "${YELLOW}Options: [q] quit, [+] more info, [-] less info, [?] help.${NC}"
+
+eval $CMDLINE
+
+unset IFS
